### PR TITLE
python2 bdist_rpm fix

### PR DESCRIPTION
**Pull request by jnaulty**
a solution for #88

### CODE REVIEW

**Comment by jnaulty** [comment]
This is just an example of how to get this to build for python2.7

I don't think it is the best solution _at all_.

**Comment by RonnyPfannschmidt** [comment]
its no solution at all, as it always runs for python2, so even if building a universal wheel everything would break

**Comment by jnaulty** [comment]
@RonnyPfannschmidt 
There is [conditional logic](https://github.com/jd/tenacity/pull/91/files#diff-2eeaed663bd0d25b7e608891384b7298R27) testing current major python release.
If it's python2 it moves the python3-specific files.

Building rpm for python3 with this includes the python3 files.

**Comment by RonnyPfannschmidt** [comment]
as per https://github.com/jd/tenacity/blob/master/setup.cfg#L26 building universal wheels is supported,
your code directly ensures those are broken for python 3 if made from python3

**Comment by jd** [comment]
While it's a nifty hack, it's clearly not the good road so I won't merge it. Feel free to reopen a PR if you ever know how to fix that.

**Comment by jnaulty** [comment]
:+1:

**Pull request closed without merging**
