### PR TITLE
Support 3.8, drop support for 2.7  [WIP]

### PR DESCRIPTION
**Pull request by hjwp**
cf #204 

sorry i know no-one asked for this and it's helicopter/driveby pullrequesting but i made a start.

### CODE REVIEW

**Comment by jd** [comment]
I don't think we want to remove 2.7 yet.
Might be possible to move the Python 3 syntaxy stuff to a different file?

**Comment by hjwp** [comment]
go on!  bump to version `6`, tell 2.7 people to pin to version 5 if they want to.  it's 2020 in 6 weeks!   :tada:

**Comment by jd** [comment]
We're already on 6 ;)

**Comment by jd** [comment]
Closing this as we don't want to remove 2.7 just yet.

**Pull request closed without merging**
