### PR TITLE
Add support for reraise

### PR DESCRIPTION
**Pull request by bodenr**
Add support for reraise as per https://github.com/jd/tenacity/issues/24

### CODE REVIEW

**Comment by bodenr** [comment]
@jd 
Looking for your thoughts before I add the UTs to doc updates.

**Comment by bodenr** [comment]
@jd comment away when you get time.

**Comment by jd** [comment]
@bodenr That looks good to me. Is there anything you want to add/edit or can I merge it?

**Comment by bodenr** [comment]
@jd I don't have anything else to add... Unless you want me to move time.sleep out of Retrying kwargs :)

**Pull request merged**
