### PR TITLE
Improved View for python snippet

### PR DESCRIPTION
**Pull request by Mgajurel**
Python snippet were not being displayed as python codes, so fixed Sphinx directives to display python snippet.

### CODE REVIEW

**Review by jd — COMMENTED** [review]
AFAIU this breaks the sphinx module that test the example though?

**Comment by Mgajurel** [comment]
Yeah, I figured that. How about we create a different Readme.md here for the Repo?

**Comment by Mgajurel** [comment]
Writing a script to convert from rst to md and have a GitHub action to automate the process, would even be better or would it be an overkill? @jd

**Comment by Mgajurel** [comment]
Should I close this PR and may be create a new one? @jd

**Pull request closed without merging**
