### PR TITLE
Add reno (changelog system)

### PR DESCRIPTION
**Pull request by goodspark**
Addresses #83 

I defer to you on particulars on configuration, formatting, process, etc. This is to just get the system up and running to start.

I'm not sure how to configure the Travis parts. reno [recommends tweaking the setup](https://docs.openstack.org/reno/latest/user/usage.html#within-travis-ci) for the build, but I don't think that's necessary for every tox-env that'll run. Just whatever is the env's docs will actually be uploaded.

screenshot from 2018-10-26 22-49-34
screenshot from 2018-10-26 22-49-40

### CODE REVIEW

**Comment by jd** [comment]
Travis' job is failing for a reason  I don't know because of the log. Sigh. Did you try locally @goodspark ?

**Comment by goodspark** [comment]
I haven't run all the Python versions but, yes, the tests pass (although the logs are really spammy). Seems like if a build generates too many logs, Travis will just abort it. Which is odd but I suppose they have a Reason.

```
 detox -e py27,py36,py37
py27 run-test-pre: PYTHONHASHSEED='3258168061'
py27 runtests: commands[0] | pytest --ignore=tenacity/tests/test_asyncio.py ''
py36 run-test-pre: PYTHONHASHSEED='3258168061'
py36 runtests: commands[0] | pytest ''
py37 run-test-pre: PYTHONHASHSEED='3258168061'
py37 runtests: commands[0] | sphinx-build -a -E -W -b doctest doc/source doc/build
py37 runtests: commands[1] | sphinx-build -a -E -W -b html doc/source doc/build
py36 runtests: commands[1] | sphinx-build -a -E -W -b doctest doc/source doc/build
py27 runtests: commands[1] | sphinx-build -a -E -W -b doctest doc/source doc/build
py36 runtests: commands[2] | sphinx-build -a -E -W -b html doc/source doc/build
py27 runtests: commands[2] | sphinx-build -a -E -W -b html doc/source doc/build
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
  py27: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
  congratulations :)
```

**Comment by jd** [comment]
Failure looks legit at first glance

**Comment by goodspark** [comment]
Aha! So it was due to shallow clones on Travis.
https://docs.openstack.org/reno/latest/user/usage.html#within-travis-ci

@jd Take another look? Looks like all the tests are passing now.

**Comment by jd** [comment]
Thanks a lot @goodspark

**Pull request merged**
