### PR TITLE
Add Context Manager methods to Retrying class

### PR DESCRIPTION
**Pull request by heri16**
Another implementation of Issue #48

### CODE REVIEW

**Comment by jd** [comment]
This needs to be squashed before I can review anyhow

**Comment by heri16** [comment]
Thought Github supports Squash on merge already? https://help.github.com/articles/about-pull-request-merges/

**Comment by jd** [comment]
Same conclusion as other PR you did, this adds 0 value to the workflow unfortunately.

**Comment by heri16** [comment]
Would you reconsider this as Syntatic Sugar? It is easier for some of my other collaborators to see `rpc('filename.txt', 'r')` than many `retrying(rpc, 'filename.txt', 'r')` littered throughout the codebase, which they claim is confusing.

**Comment by heri16** [comment]
Also AsyncRetrying does not support __call__, so it makes the syntax even more verbose.

**Comment by jd** [comment]
You can do `rpc = retry(rpc, someargs); rpc('filename.txt', 'r')`. No need for `with`.

**Pull request closed without merging**
