### PR TITLE
Add a __repr__ method to RetryCallState objects

### PR DESCRIPTION
**Pull request by zbentley**
Many folks use tools which dump locals when an exception occurs. For example, I use Sentry quite frequently to dig around in the stack below an exception to see what happened and what went wrong. Many of those stack-debugging tools stringify (via `__repr__`ing each local) and send the results to some sort of debugging console/webpage.

When I encounter a Tenacity-retried function in my call stack, I can poke around inside Tenacity's locals a bit to see what went wrong, but I can't tell much about what caused Tenacity to give up, since all I can see of the retry call state object is e.g. `<tenacity.RetryCallState object at 0x7f99fe9119a0>`. That's not terribly useful.

This PR adds a `__repr__` method to RetryCallState so that stringifications of those objects now contain some information useful for human debuggers--how many times something has been retried, how long Tenacity has slept for, and what the result of the last attempt (if any) was.

### CODE REVIEW

**Review by jd — CHANGES_REQUESTED** [review]
That's a good idea. Would you mind adding a changelog entry and some tests?

**Comment by zbentley** [comment]
@jd I am happy to; mobile until the 19th and then will pick this up. Thanks for the response and excellent library!

**Review by jd — APPROVED** [review]

**Review by jd — APPROVED** [review]

**Comment by zbentley** [comment]
@jd something about my tests appears to be merge conflicting. Did I perhaps run the wrong version of `black` on them or something similar?

**Comment by penguinolog** [comment]
`black` changed formatting in 2021 year versions

**Review by penguinolog — COMMENTED** [review]
@zbentley `tenacity/tests/test_tenacity.py` has been moved to `tests/test_tenacity.py`, it's reason for merge conflicts

**Comment by zbentley** [comment]
@penguinolog all set, thanks!

**Review by penguinolog — APPROVED** [review]

**Review by jd — APPROVED** [review]

**Pull request merged**
