### PR TITLE
Before sleep log stack info

### LINKED ISSUE #290: Allow stack_info argument in before_sleep_log strategy
#227 adds the `exc_info` parameter to the `before_sleep_log()` function.  This is nice, but the stack trace ends at the place where the exception is raised.  It may be useful to have the entire stack context as part of the log by allowing the stack_info argument to the logger.

See description in the logging documentation:

> The second optional keyword argument is stack_info, which defaults to False. If true, stack information is added to the logging message, including the actual logging call. Note that this is not the same stack information as that displayed through specifying exc_info: The former is stack frames from the bottom of the stack up to the logging call in the current thread, whereas the latter is information about stack frames which have been unwound, following an exception, while searching for exception handlers.

> You can specify stack_info independently of exc_info, e.g. to just show how you got to a certain point in your code, even when no exceptions were raised. The stack frames are printed following a header line which says:

`Stack (most recent call last):`

> This mimics the Traceback (most recent call last): which is used when displaying exception frames.

Note, I have this coded up.  Just let me know if this is okay and I can open a PR.

### PR DESCRIPTION
**Pull request by jpark712**
This change adds the `stack_info` parameter to the before_sleep_log() function and passes it to the logger function.  When set to True, logger will include a stack dump at the current location, which can be useful to pinpointing the exact location in code that triggered a retry.

Closes #290

### CODE REVIEW

**Comment by jpark712** [comment]
Example of before_sleep_log called with exc_info=True, stack_info=False:

```
test_func called()
INFO:__main__:Retrying __main__.test_func in 1.0 seconds as it raised Exception: my error.
Traceback (most recent call last):
  File "C:\github\forks\tenacity\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File ".\ten.py", line 35, in test_func
    raise Exception("my error")
Exception: my error
```

Example of before_sleep_log called with exc_info=True, stack_info=True.  Notice we can now see that test_func was called from line 117 from the main() method whereas before, we only get the line that raised the exception.
```
test_func called()
INFO:__main__:Retrying __main__.test_func in 1.0 seconds as it raised Exception: my error.
Traceback (most recent call last):
  File "C:\github\forks\tenacity\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File ".\ten.py", line 35, in test_func
    raise Exception("my error")
Exception: my error
Stack (most recent call last):
  File ".\ten.py", line 117, in <module>
    main()
  File ".\ten.py", line 94, in main
    r.call(test_func, 1, 2)
  File "C:\github\forks\tenacity\tenacity\__init__.py", line 419, in call
    return self.__call__(*args, **kwargs)
  File "C:\github\forks\tenacity\tenacity\__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\github\forks\tenacity\tenacity\__init__.py", line 391, in iter
    self.before_sleep(retry_state=retry_state)
  File "C:\github\forks\tenacity\tenacity\before_sleep.py", line 41, in log_it
    logger.log(
```

**Review by jd — APPROVED** [review]

**Comment by jd** [comment]
Ah I think CI is broken again. Really need to move to GH Actions.

**Comment by RoyalTS** [comment]
This would be super useful to have. Is there any chance of landing this soon?

**Comment by jd** [comment]
Old and in conflict, closing.

**Pull request closed without merging**
