### PR TITLE
Fix asyncio.iscoroutinefunction(f) check for decorated function

### PR DESCRIPTION
**Pull request by SlavaSkvortsov**
It was fixed [here](https://github.com/adjust/tenacity/commit/3bae79e71519ed1a34cea53dcf98903ef02eb6c7), but the fix was removed [here](https://github.com/adjust/tenacity/commit/66de0110844a742b820ab6c1f29edb19ed2e5908) (I think accidentally)

Fixes: https://github.com/jd/tenacity/issues/224

### CODE REVIEW

**Review by jd — APPROVED** [review]

**Comment by jd** [comment]
@mergifyio update

**Comment by jd** [comment]
@Mergifyio update

**Comment by jd** [comment]
Looks like I don't have write access to this PR? Might be why CircleCI didn't run?
Could you rebase it @SlavaSkvortsov?

**Comment by SlavaSkvortsov** [comment]
@jd rebased

**Comment by jd** [comment]
CircleCI is still ignoring it. No clue why.

**Comment by SlavaSkvortsov** [comment]
You can just do a PR by yourself, I don't mind :)

**Pull request closed without merging**
